"""add recommendation statuses

Revision ID: dfd2882d9e70
Revises: b7fd5cb1ab35
Create Date: 2026-10-09 11:00:19.128901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd2882d9e70'
down_revision: Union[str, None] = 'b7fd5cb1ab35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommendation_id', name='uq_recommendation_statuses_user_rec')
    )
    op.create_index(op.f('ix_recommendation_statuses_user_id'), 'recommendation_statuses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_statuses_user_id'), table_name='recommendation_statuses')
    op.drop_table('recommendation_statuses')
    # ### end Alembic commands ###
