"""add document extraction and itr autofill

Revision ID: f12976c639ec
Revises: 2c3b702b1e2f
Create Date: 2026-10-01 16:13:35.607744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f12976c639ec'
down_revision: Union[str, None] = '2c3b702b1e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extraction_status', sa.String(length=16), nullable=False, server_default='not_applicable'))
    op.add_column('documents', sa.Column('extraction_message', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('itr_filings', sa.Column('autofill', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itr_filings', 'autofill')
    op.drop_column('documents', 'extracted')
    op.drop_column('documents', 'extraction_message')
    op.drop_column('documents', 'extraction_status')
    # ### end Alembic commands ###
