"""
Plain-language explanation of a tax regime comparison, generated by OpenAI.

This is enrichment, not the source of truth: every number it talks about was
already computed deterministically in calculator.py/service.py. The model is
instructed to restate those numbers, never recompute or invent them, and the
response is constrained to a fixed JSON shape via structured outputs, with a
low temperature as a secondary grounding measure.

Any failure here (missing API key, network error, rate limit, bad response)
falls back to a deterministic templated explanation built straight from the
comparison numbers — the explanation is never allowed to block or fail the
underlying tax calculation.
"""

import json
import logging

import openai

from app.core.config import get_settings
from app.modules.tax import ai_guardrails
from app.modules.tax.context import comparison_context
from app.modules.tax.schemas import ExplanationResult, TaxComparisonResult

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """\
You help first-time Indian salaried taxpayers understand a tax regime \
comparison. You will be given the exact numbers from a completed \
calculation as JSON, including which deduction categories they declared.

Rules:
- Every number you mention must come verbatim from the JSON you are given. \
Never compute, round, or guess a number yourself.
- If a number you'd want isn't in the JSON, omit it rather than estimate it.
- Write in plain, first-principles language for someone with no finance \
background — no jargon like "slab", "cess", or "rebate" without a one-clause \
explanation the first time you use it.
- Write two short, separate notes (1-2 sentences each) — each is shown \
inside that regime's own card on screen, so it must stand alone without \
referencing the other regime by name:
  - new_regime_note: when the New Regime suits someone like this. State its \
estimated tax figure. It usually suits people with few or no deductions to \
claim, since it only applies a flat standard deduction.
  - old_regime_note: when the Old Regime suits someone like this. State its \
estimated tax figure. If deduction categories were declared (check the \
deduction_checklist), reference those categories by name (e.g. "since you've \
declared amounts under 80C and HRA") — do not invent categories that have \
zero declared_amount. If none were declared, say this regime only pays off \
if they actually hold investments/proofs under categories like 80C, 80D, \
HRA, home loan interest, or NPS.
- The old_regime_disclaimer must say plainly that the old-regime tax figure \
assumes the person actually holds the investments/proofs they declared, and \
that nothing is deducted automatically — proofs are required at filing time.
- This is objective calculation, not personalized financial advice. Only \
refer to deduction *categories* already present in the data (80C, 80D, HRA, \
home loan interest, NPS) — never recommend specific funds, products, or \
investment amounts.
"""

_EXPLANATION_SCHEMA = {
    "type": "object",
    "properties": {
        "old_regime_note": {"type": "string"},
        "new_regime_note": {"type": "string"},
        "old_regime_disclaimer": {"type": "string"},
    },
    "required": ["old_regime_note", "new_regime_note", "old_regime_disclaimer"],
    "additionalProperties": False,
}


def _build_user_prompt(comparison: TaxComparisonResult) -> str:
    payload = comparison_context(comparison)
    return (
        "Here is the completed tax comparison, as JSON. Write the two notes "
        "and the old_regime_disclaimer described in your instructions.\n\n"
        f"{json.dumps(payload)}"
    )


def _declared_categories(comparison: TaxComparisonResult) -> list[str]:
    return [item.label for item in comparison.deduction_checklist if item.declared_amount > 0]


def _fallback(comparison: TaxComparisonResult) -> ExplanationResult:
    old_tax = comparison.old_regime.total_tax_payable
    new_tax = comparison.new_regime.total_tax_payable
    declared = _declared_categories(comparison)

    if declared:
        old_regime_note = (
            f"Estimated tax here is ₹{old_tax:,}, assuming you actually hold the investments "
            f"or proofs you declared under {', '.join(declared)}."
        )
    else:
        old_regime_note = (
            f"Estimated tax here is ₹{old_tax:,}. This regime only pays off if you hold "
            f"investments or proofs under sections like 80C, 80D, HRA, home loan interest, "
            f"or NPS — you haven't declared any yet."
        )

    new_regime_note = (
        f"Estimated tax here is ₹{new_tax:,}. This regime applies a flat standard deduction "
        f"only — no proofs or investment declarations needed."
    )

    disclaimer = (
        "This old-regime estimate assumes you actually hold the investments and proofs "
        "you declared (80C, 80D, HRA, home loan interest, NPS). Nothing is deducted "
        "automatically — you'll need the documentation on hand when you file."
    )
    return ExplanationResult(
        old_regime_note=old_regime_note,
        new_regime_note=new_regime_note,
        old_regime_disclaimer=disclaimer,
    )


def generate_explanation(comparison: TaxComparisonResult) -> ExplanationResult:
    settings = get_settings()
    if not settings.openai_api_key:
        return _fallback(comparison)

    client = openai.OpenAI(api_key=settings.openai_api_key, timeout=15.0)
    try:
        response = client.chat.completions.create(
            model=settings.openai_model,
            temperature=0.2,
            max_completion_tokens=500,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT + ai_guardrails.POLICY},
                {"role": "user", "content": _build_user_prompt(comparison)},
            ],
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": "tax_explanation",
                    "schema": _EXPLANATION_SCHEMA,
                    "strict": True,
                },
            },
        )
        text = response.choices[0].message.content
        if text is None:
            raise ValueError("empty response content")
        data = json.loads(text)
        return ExplanationResult(**data)
    except (openai.APIStatusError, openai.APIConnectionError, ValueError, IndexError) as exc:
        logger.warning("Falling back to templated tax explanation: %s", exc)
        return _fallback(comparison)
